[package]
name = "turing_machine"
version = "0.1.0"
authors = ["h04x <liquid.doctrine@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.0"
